language: python

stages:
  - lint
  - test

before_install:
- pip install codecov
install:
- pip install tox-travis

script: tox

jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      after_success:
        - codecov

    - stage: lint
      python: "3.7"
      script:
        - tox -e lint,isort-check,black-check
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: ...travis encrypt --add deploy.password...
  on:
    tags: true
    all_branches: true
